---
layout: post
title: Preserving stack trace when catching and re-raising runtime exceptions
date: '2013-08-26T00:26:00.000+01:00'
author: Thomas Tempelmann
tags:
- Xojo
modified_time: '2013-08-26T00:26:18.588+01:00'
blogger_id: tag:blogger.com,1999:blog-8797526579651167122.post-7554693420145283950
blogger_orig_url: https://blog.tempel.org/2013/08/preserving-stack-trace-when-catching.html
---

<span style="font-family: Arial, Helvetica, sans-serif;">(This is a repost of an article of mine on Real Software's, now Xojo Inc's,&nbsp;</span><a href="http://www.realsoftwareblog.com/" style="font-family: Arial, Helvetica, sans-serif;" target="_blank">former blog</a><span style="font-family: Arial, Helvetica, sans-serif;">)</span><br /><span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><span style="font-family: Arial, Helvetica, sans-serif;">This post offers an introduction to the usefulness of exception handling in general, while also explaining how to deal with a particular shortcoming when you use debugging code and the UnhandledException event handler in built programs you deliver to people. I hope this article will be helpful to both newcomers and veterans alike.</span><br /><span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><span style="font-family: Arial, Helvetica, sans-serif;"><b>Background (UnhandledException and the Stack Trace)</b></span><span style="font-family: Arial, Helvetica, sans-serif;"><b><br /></b></span><br /><span style="font-family: Arial, Helvetica, sans-serif;"><b><br /></b></span><span style="font-family: Arial, Helvetica, sans-serif;">You probably know the <b>UnhandledException</b> event handler in the <b>App</b> class.</span><span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /> <span style="font-family: Arial, Helvetica, sans-serif;">It lets you catch any unhandled exceptions in your program, preventing your program from getting terminated unexpectedly, and allowing you to save any interim data that the user may have not saved yet, and other defensive fallback procedures.</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">One other use of this handler is to record the location where the exception occurred in order to use that for later debugging. For instance, if you send your built application to others who do not have the Xojo debugger, your program could still record the so-called stack trace from the exception, show that to the user, and ask him to forward that information to you so you can hopefully deduce what went wrong and how to avoid it in the future.</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">You get this stack trace by invoking the <b>Stack()</b> method of the <b>RuntimeException</b> object you get passed in UnhandledException. It returns an array of strings, identifiying the methods that were called up to the one that caused the exception.</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">For instance, if your program causes an exception in a Window's Open event, the stack trace might look like this:</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: 'Courier New', Courier, monospace;">1. RaiseOutOfBoundsException</span><br /><span style="font-family: 'Courier New', Courier, monospace;">2. Window1.Window1.Event_Open%%o&lt;Window1.Window1&gt;</span><br /><span style="font-family: 'Courier New', Courier, monospace;">3. FireWindowOpenEvents</span><br /><span style="font-family: 'Courier New', Courier, monospace;">4. Window.Constructor%%o&lt;Window&gt;</span><br /><span style="font-family: 'Courier New', Courier, monospace;">5. Window1.Window1%o&lt;Window1.Window1&gt;%</span><br /><span style="font-family: 'Courier New', Courier, monospace;">6. _MakeDefaultView</span><br /><span style="font-family: 'Courier New', Courier, monospace;">7. _Startup</span><br /><span style="font-family: 'Courier New', Courier, monospace;">8. RunFrameworkInitialization</span><br /><span style="font-family: 'Courier New', Courier, monospace;">9. REALbasic._RunFrameworkInitialization%%p</span><br /><span style="font-family: 'Courier New', Courier, monospace;">10. _Main</span><br /><span style="font-family: 'Courier New', Courier, monospace;">11. % main</span><br /><span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><span style="font-family: Arial, Helvetica, sans-serif;">The topmost line shows where the exception occured, the bottommost is the topmost caller at that time.</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">It tells several things:</span><br /><br /><ul><li><span style="font-family: Arial, Helvetica, sans-serif;">The exception, obviously an&nbsp;<b><i>OutOfBounds</i></b> exception, occured in Window1's Open event (line #2)</span></li><li><span style="font-family: Arial, Helvetica, sans-serif;">The Open event was invoked by the Window1's Constructor (lines 4 and 5).</span></li><li><span style="font-family: Arial, Helvetica, sans-serif;">The Window1 got constructed right at start of the program (line 7). Otherwise, we'd usually see the method "RuntimeRun" up in the stack trace, indicating that the startup has finished and the program is now processing events.</span></li></ul><br /><br /> <span style="font-family: Arial, Helvetica, sans-serif;"><b>Raising exceptions</b></span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">Whenever an exception occurs, we say that it gets raised. Xojo even offers a custom statement for that: The <i><b>Raise</b></i> command. With that, you can make your own exceptions occur. An example:</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">&nbsp;</span><span style="font-family: 'Courier New', Courier, monospace;">&nbsp;raise new OutOfBoundsException</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">is equivalent to:</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">&nbsp;</span><span style="font-family: 'Courier New', Courier, monospace;">&nbsp;dim anArray(0) as Integer</span><br /><span style="font-family: 'Courier New', Courier, monospace;"><span class="Apple-style-span" style="font-family: Times;"><span style="font-family: Arial, Helvetica, sans-serif;">&nbsp;</span></span><span class="Apple-style-span" style="font-family: Times;"><span style="font-family: 'Courier New', Courier, monospace;">&nbsp;</span></span>anArray(1) = 0 // this will cause an OutOfBoundsException</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">(Of course, you can create your very own exception types by subclassing them from RuntimeException. See the&nbsp;<a href="http://docs.xojo.com/index.php/Category:Errors_Runtime_Errors" target="_blank">Language Reference</a>&nbsp;to learn more about that.)</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">Now, here's an imporant part: The stack trace that gets attached to any RuntimeException object is created when this raise statement is invoked. And the stack trace is then created from the very calling stack that's in effect at the time of invocation. Logical, right?</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;"><b><br /></b></span><span style="font-family: Arial, Helvetica, sans-serif;"><b>Catching exceptions</b></span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">You can catch exceptions in your methods using the&nbsp;</span><span style="font-family: 'Courier New', Courier, monospace;">try ... catch ... end</span><span style="font-family: Arial, Helvetica, sans-serif;">&nbsp;and the exception statements.</span><br /><span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><span style="font-family: Arial, Helvetica, sans-serif;">There are two common cases why and how you'd catch exceptions:</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /> <span style="font-family: Arial, Helvetica, sans-serif;"><b>1. Handling the exception</b></span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">You expect a particular exception to occur and are prepared to handle it. This is, for instance, the case when you use file I/O operations and which you cannot otherwise predict to avoid them, such as that a file cannot be created, causing an IOException.</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /> <span style="font-family: Arial, Helvetica, sans-serif;"><b>2. Cleanup</b></span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">You do not know that any particular exceptions might occur in some subroutines you call but you like to be prepared and do some cleanup if that should happen. In this case, you'll pass on the exception to the caller because you don't know have reason way to handle the exception at that particular point.</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">Such cleanup handling code usually looks like this:</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: 'Courier New', Courier, monospace;">&nbsp;try</span><br /><span style="font-family: 'Courier New', Courier, monospace;">&nbsp;</span><span class="Apple-style-span" style="font-family: 'Courier New', Courier, monospace;">&nbsp;</span><span class="Apple-style-span" style="font-family: 'Courier New', Courier, monospace;">&nbsp;.</span><span class="Apple-style-span" style="font-family: 'Courier New', Courier, monospace;">.. // your operations</span><br /><span style="font-family: 'Courier New', Courier, monospace;">&nbsp;catch exc as RuntimeException</span><br /><span style="font-family: 'Courier New', Courier, monospace;">&nbsp;</span><span class="Apple-style-span" style="font-family: 'Courier New', Courier, monospace;">&nbsp;</span><span class="Apple-style-span" style="font-family: 'Courier New', Courier, monospace;">&nbsp;</span><span style="font-family: 'Courier New', Courier, monospace;">db.Rollback // e.g. abort a database transaction</span><br /><span style="font-family: 'Courier New', Courier, monospace;">&nbsp;</span><span class="Apple-style-span" style="font-family: 'Courier New', Courier, monospace;">&nbsp;</span><span class="Apple-style-span" style="font-family: 'Courier New', Courier, monospace;">&nbsp;</span><span style="font-family: 'Courier New', Courier, monospace;">raise exc // pass the exception on</span><br /><span style="font-family: 'Courier New', Courier, monospace;">&nbsp;end</span><br /><span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><span style="font-family: Arial, Helvetica, sans-serif;"><b>The complication (catching and re-raising)</b></span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">Let's assume you have a <b>UnhandledException</b> event handler in the App class, which reads the Stack array and for later analysis (e.g. by writing to a file, creating an email to you or even uploading it to your web server).</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">So, if any part of your program raised an exception for which you don't have particular handling code, it'll end up in <b>App.UnhandledException</b>, which will eventually allow you to learn where the crash ocurred. That's the general idea, at least.</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;"><i>However:</i></span><br /><span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><span style="font-family: Arial, Helvetica, sans-serif;">Consider what happens if an exception occurs inside a subroutine that's called by code using the&nbsp;<b><i>Cleanup</i></b>&nbsp;exception handler?</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">Remember how the stack trace gets created: During the invocation of the raise statement.</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">This means that if an exception occurs deeper down, then gets caught by the Cleanup handler code, which then re-raises the exception to end up finally in the <b>App.UnhandledException</b> handler, you'll get to see the wrong Stack trace. You won't see the methods that were actually the cause of the exception but only the stack trace from the upmost raise call.</span><span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><span style="font-family: Arial, Helvetica, sans-serif;"><b>The solution</b></span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">Finally, we're getting to the root of this article's purpose.</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">I'm suggesting that whenever you have a raise exc call in your code, you change that to:</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">&nbsp;&nbsp;</span><span style="font-family: 'Courier New', Courier, monospace;">raise new CaughtException (exc)</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">And, of course, you'll need a new class&nbsp;</span><span style="font-family: 'Courier New', Courier, monospace;">CaughtException</span><span style="font-family: Arial, Helvetica, sans-serif;">&nbsp;which I'll show you here:</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">First, create a new Class, name it <b><i>CaughtException</i></b>&nbsp;and set its Super class to <b><i>RuntimeException</i></b>.</span><br /><span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><span style="font-family: Arial, Helvetica, sans-serif;">Then add the following two methods to it:</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">&nbsp;</span><span style="font-family: 'Courier New', Courier, monospace;">&nbsp;Sub Constructor(exc as RuntimeException)</span><br /><span style="font-family: 'Courier New', Courier, monospace;">&nbsp; &nbsp;&nbsp;if exc isA CaughtException then</span><br /><span style="font-family: 'Courier New', Courier, monospace;">&nbsp; &nbsp; &nbsp; exc = CaughtException(exc).OrigExc</span><br /><span style="font-family: 'Courier New', Courier, monospace;">&nbsp; &nbsp; end</span><br /><span style="font-family: 'Courier New', Courier, monospace;">&nbsp; &nbsp; self.OrigExc = exc</span><br /><span style="font-family: 'Courier New', Courier, monospace;">&nbsp; End Sub</span><br /><span style="font-family: 'Courier New', Courier, monospace;">&nbsp;&nbsp;</span><br /><span style="font-family: 'Courier New', Courier, monospace;">&nbsp; Function Stack() As String()</span><br /><span style="font-family: 'Courier New', Courier, monospace;">&nbsp; &nbsp; return self.OrigExc.Stack</span><br /><span style="font-family: 'Courier New', Courier, monospace;">&nbsp; End Function</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">Finally, add this private property:</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">&nbsp;&nbsp;</span><span style="font-family: 'Courier New', Courier, monospace;">OrigExc As RuntimeException</span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">That's all you need to care about.</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">The trick here is that this class overwrites the <b>Stack()</b> method of <b>RuntimeException</b>, providing the original stack trace instead of the (useless) one created by the raise command. Therefore, your <b>App.UnhandledException</b> handler won't have to be changed at all to make this work.</span>&nbsp;<span style="font-family: Arial, Helvetica, sans-serif;"><br /></span><br /><br /><span style="font-family: Arial, Helvetica, sans-serif;">Even if you do not fully comprehend what this is doing, simply follow my advice of always using this construct wherever you catch an exception and raise it right after again. It'll magically make your debugging efforts easier in the future.</span>